#application: prjname
#version: 1.25
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "latest"

handlers:

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico


######  config start  ######

- url: /[subdir4bg]/example1
  script: example1.app		
- url: /[subdir4rss]/example1
  script: feed_list.example1	

- url: /[subdir4bg]/example2
  script: example2.app		
- url: /[subdir4rss]/example2
  script: feed_list.example2	

######  config end  ######
