#application: prjname
#version: 1.25
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "latest"

handlers:

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico


######  config start  ######

- url: /[subdir4bg]/example
  script: example.app		
- url: /[subdir4rss]/example
  script: feed_list.example1

- url: /[subdir4rss]/example_02
  script: example_02.app		
#For example_02 is not necessary to add it in feed_list.py and cron.yaml, because the feed will not save in cloud storage.

######  config end  ######
